[package]
authors = ["Simon Persson <simon@flaskpost.org>", "Sven Lechner <sven.lechner@rwth-aachen.de>"]
edition = "2018"
name = "spotifyd"
description = "A Spotify daemon"
repository = "https://github.com/Spotifyd/spotifyd"
license = "GPL-3.0-only"
version = "0.2.25"

[dependencies]
alsa = { version = "0.3", optional = true }
chrono = "0.4.19"
daemonize = "0.4.1"
dbus = { version = "0.6", optional = true }
dbus-tokio = { version = "0.2", optional = true }
fern = { version = "0.6.0", features = ["syslog-4"] }
futures = "0.1"
gethostname = "0.2.1"
hex = "0.4.2"
keyring = { version = "0.9.0", optional = true }
libc = "0.2.79"
log = "0.4.11"
percent-encoding = "2.1.0"
rspotify = { version = "0.10.0", features = ["blocking"] }
serde = { version = "1.0.117", features = ["derive"] }
sha-1 = "0.9.1"
structopt = "0.3.20"
syslog = "4.0.1"
tokio-core = "0.1.17"
tokio-io = "0.1.13"
tokio-signal = "0.2.9"
url = "1.7"
xdg = "2.2.0"
librespot = { version = "0.1.3", default-features = false, features = ["with-tremor"] }
toml = "0.5.7"

[target."cfg(target_os = \"macos\")".dependencies]
whoami = "0.9.0"

[dev-dependencies]
env_logger = "0.8.1"

[features]
alsa_backend = ["librespot/alsa-backend", "alsa"]
dbus_keyring = ["keyring"]
dbus_mpris = ["dbus", "dbus-tokio"]
default = ["alsa_backend"]
portaudio_backend = ["librespot/portaudio-backend"]
pulseaudio_backend = ["librespot/pulseaudio-backend"]
rodio_backend = ["librespot/rodio-backend"]

[package.metadata.deb]
depends = "$auto, systemd, pulseaudio"
features = [
    "pulseaudio_backend",
    "dbus_keyring",
    "dbus_mpris",
]
assets = [
    ["target/release/spotifyd", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/spotifyd/README", "644"],
    ["contrib/spotifyd.service", "etc/systemd/user/", "644"],
]
