# First build from the cross repo with ./build-docker-image.sh armv7-unknown-linux-gnueabihf
FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:local

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install --assume-yes libasound2-dev:armhf libssl-dev:armhf libdbus-1-dev:armhf

ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig/

